import { LoaderCircle } from "lucide-react";
import { useEffect, useState } from "react";
import { api } from "../lib/api";

const Card = ({ label, value, detail }) => <section className="glass-card rounded-lg"><p className="text-sm text-text-secondary">{label}</p><p className="mt-4 text-4xl font-bold">{value}</p><p className="mt-2 text-sm text-text-secondary">{detail}</p></section>;

export default function Admin() {
  const [stats, setStats] = useState(null);
  const [companies, setCompanies] = useState([]);
  const [users, setUsers] = useState([]);
  const [error, setError] = useState("");
  const [busy, setBusy] = useState("");
  const load = () => Promise.all([api("/api/admin/system-stats"), api("/api/admin/companies"), api("/api/admin/users")]).then(([systemStats, companyList, userList]) => { setStats(systemStats); setCompanies(companyList || []); setUsers(userList || []); }).catch((cause) => setError(cause.message));
  useEffect(() => { load(); }, []);
  async function changeRole(userId, role) { setBusy(userId); try { await api(`/api/admin/users/${userId}/role`, { method: "PATCH", body: JSON.stringify({ role }) }); await load(); } catch (cause) { setError(cause.message); } finally { setBusy(""); } }
  async function suspend(companyId) { setBusy(companyId); try { await api(`/api/admin/companies/${companyId}/suspend`, { method: "PATCH" }); await load(); } catch (cause) { setError(cause.message); } finally { setBusy(""); } }
  return <><div><h1 className="text-3xl font-bold">Admin command center</h1><p className="mt-2 text-sm text-text-secondary">Monitor all CRM workspaces, users, customer volume, campaigns, and AI activity.</p></div>{error && <p className="mt-3 text-sm text-rose-300">{error}</p>}<div className="mt-7 grid gap-5 lg:grid-cols-3"><Card label="Active workspaces" value={stats?.active_companies ?? 0} detail="Non-suspended company accounts" /><Card label="Agent runs" value={stats?.total_runs ?? 0} detail="Queued, running, completed, and failed" /><Card label="Recorded credits" value={stats?.total_credits_used ?? 0} detail="Usage tracked by agent runs" /></div><section className="glass-card mt-7 overflow-x-auto rounded-lg"><h2 className="text-xl font-semibold">All users</h2><table className="mt-4 w-full text-left text-sm"><thead className="text-text-secondary"><tr><th>Email</th><th>Workspace</th><th>Role</th><th>Plan</th><th>Access</th></tr></thead><tbody>{users.map((item) => <tr key={item.id} className="border-t border-border-subtle"><td className="py-3">{item.email}</td><td>{item.company_name || "-"}</td><td><select value={item.role} disabled={busy === item.id} onChange={(event) => changeRole(item.id, event.target.value)} className="rounded border border-border bg-bg-base p-2"><option value="company">Company</option><option value="csm">CSM</option><option value="viewer">Viewer</option><option value="admin">Admin</option></select></td><td>{item.plan}</td><td className={item.suspended ? "text-rose-300" : "text-emerald-300"}>{item.suspended ? "Suspended" : "Active"}</td></tr>)}</tbody></table>{!users.length && <p className="mt-4 text-sm text-text-secondary">No users yet.</p>}</section><section className="glass-card mt-7 overflow-x-auto rounded-lg"><h2 className="text-xl font-semibold">Company workspaces</h2><table className="mt-4 w-full text-left text-sm"><thead className="text-text-secondary"><tr><th>Company</th><th>Customers</th><th>Campaigns</th><th>Agent runs</th><th /></tr></thead><tbody>{companies.map((item) => <tr key={item.company.id} className="border-t border-border-subtle"><td className="py-3">{item.company.company_name || item.company.email}</td><td>{item.customer_count}</td><td>{item.campaign_count}</td><td>{item.agent_run_count}</td><td>{item.company.suspended ? <span className="text-rose-300">Suspended</span> : <button disabled={busy === item.company.id} onClick={() => suspend(item.company.id)} className="inline-flex items-center gap-2 text-rose-300">{busy === item.company.id && <LoaderCircle size={14} className="animate-spin" />}Suspend</button>}</td></tr>)}</tbody></table>{!companies.length && <p className="mt-4 text-sm text-text-secondary">No company workspaces yet.</p>}</section></>;
}
