import { LoaderCircle, Star, X } from "lucide-react";
import { useEffect, useState } from "react";
import { api } from "../lib/api";

const types = [["churn_analysis", "Churn scorer"], ["root_cause", "Root cause analyst"], ["outreach_draft", "Outreach drafter"], ["health_scoring", "Health updater"]];

function RunOutput({ output }) {
  if (!output) return <p className="mt-3 text-sm text-text-secondary">The agent has not produced output yet.</p>;
  if (Array.isArray(output.updated_customers)) return <div className="mt-4 grid gap-3 md:grid-cols-2">{output.updated_customers.map((item) => { const score = Number(item.health_score || 0); const stars = Math.max(1, Math.min(5, Math.ceil(score / 20))); return <div key={item.customer_id} className="rounded-lg border border-border-subtle bg-bg-base p-3"><div className="flex items-center justify-between"><span className="font-medium">Customer {String(item.customer_id).slice(0, 8)}</span><span className="flex">{Array.from({ length: 5 }, (_, index) => <Star key={index} size={14} className={index < stars ? "fill-amber-400 text-amber-400" : "text-slate-700"} />)}</span></div><p className="mt-2 text-sm text-text-secondary">Health score: {score}/100</p>{item.reason && <p className="mt-2 text-sm">{item.reason}</p>}</div>; })}</div>;
  if (Array.isArray(output.top_causes)) return <div className="mt-4 grid gap-5 md:grid-cols-2"><div><h3 className="font-medium">Evidence-bound causes</h3><ul className="mt-2 space-y-2 text-sm text-text-secondary">{output.top_causes.map((cause) => <li key={cause}>{cause}</li>)}</ul></div><div><h3 className="font-medium">Recommended actions</h3><ul className="mt-2 space-y-2 text-sm text-text-secondary">{(output.recommended_actions || []).map((action) => <li key={action}>{action}</li>)}</ul></div></div>;
  return <pre className="mt-4 max-h-80 overflow-auto rounded-lg border border-border-subtle bg-bg-base p-3 text-xs text-text-secondary">{JSON.stringify(output, null, 2)}</pre>;
}

export default function AgentRuns() {
  const [runs, setRuns] = useState([]);
  const [selectedRun, setSelectedRun] = useState(null);
  const [busyType, setBusyType] = useState("");
  const [cancellingId, setCancellingId] = useState("");
  const [error, setError] = useState("");
  const load = async (showError = false) => { try { const result = await api("/api/agents/runs"); setRuns(result || []); setSelectedRun((current) => current ? (result || []).find((run) => run.id === current.id) || current : null); } catch (cause) { if (showError) setError(cause.message); } };
  useEffect(() => { load(); const id = setInterval(load, 5000); return () => clearInterval(id); }, []);

  async function launch(type) { if (busyType) return; setBusyType(type); setError(""); try { const run = await api("/api/agents/run", { method: "POST", body: JSON.stringify({ type, config: {} }) }); setSelectedRun(run); await load(); } catch (cause) { setError(cause.message); } finally { setBusyType(""); } }
  async function cancel(runId) { if (cancellingId) return; setCancellingId(runId); setError(""); try { const run = await api(`/api/agents/runs/${runId}/cancel`, { method: "POST" }); setSelectedRun((current) => current?.id === run.id ? run : current); await load(); } catch (cause) { setError(cause.message); } finally { setCancellingId(""); } }

  return <><h1 className="text-3xl font-bold">Agent Runs</h1><p className="mt-2 text-sm text-text-secondary">Runs continue in the background while you work elsewhere. Cancel queued or running work at any time.</p>{error && <p className="mt-3 text-sm text-rose-300">{error}</p>}<div className="mt-7 grid gap-5 md:grid-cols-2">{types.map(([type, label]) => <section key={type} className="glass-card rounded-lg"><h2 className="text-xl font-semibold">{label}</h2><button disabled={Boolean(busyType)} onClick={() => launch(type)} className="mt-6 inline-flex min-h-11 items-center gap-2 rounded-lg bg-accent-primary px-5 py-3 disabled:opacity-60">{busyType === type && <LoaderCircle size={16} className="animate-spin" />}{busyType === type ? "Queueing..." : "Launch run"}</button></section>)}</div><section className="glass-card mt-7 rounded-lg"><h2 className="text-xl font-semibold">Recent runs</h2>{runs.map((run) => <div key={run.id} className="mt-4 flex w-full items-center justify-between gap-3 border-t border-border-subtle pt-4 text-left text-sm"><button type="button" onClick={() => setSelectedRun(run)} className="min-w-0 flex-1 text-left"><span className="block capitalize">{run.type.replaceAll("_", " ")}</span><span className={run.status === "complete" ? "text-emerald-300" : ["failed", "cancelled"].includes(run.status) ? "text-rose-300" : "text-amber-300"}>{run.status}</span></button>{["queued", "running"].includes(run.status) && <button type="button" onClick={() => cancel(run.id)} disabled={Boolean(cancellingId)} className="inline-flex min-h-9 items-center gap-1 rounded-lg border border-border px-3 text-rose-200 disabled:opacity-60">{cancellingId === run.id ? <LoaderCircle size={14} className="animate-spin" /> : <X size={14} />}{cancellingId === run.id ? "Cancelling" : "Cancel"}</button>}</div>)}{!runs.length && <p className="mt-4 text-sm text-text-secondary">No runs yet. Select customers first for a focused churn analysis.</p>}</section>{selectedRun && <section className="glass-card mt-7 rounded-lg"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-semibold">Run analysis</h2><p className="mt-1 text-sm text-text-secondary">{selectedRun.type.replaceAll("_", " ")} - {selectedRun.status}</p></div><span className="text-sm text-text-secondary">{String(selectedRun.id).slice(0, 8)}</span></div><RunOutput output={selectedRun.output} /></section>}</>;
}
