import { KeyRound, LoaderCircle, UserRound } from "lucide-react";
import { useState } from "react";
import { useAuth } from "../lib/auth-context";

export default function Settings() {
  const { user, updateProfile } = useAuth();
  const [email, setEmail] = useState(user?.email || ""); const [username, setUsername] = useState(user?.username || ""); const [companyName, setCompanyName] = useState(user?.company_name || ""); const [currentPassword, setCurrentPassword] = useState(""); const [newPassword, setNewPassword] = useState(""); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [saving, setSaving] = useState(false);
  async function save(event) { event.preventDefault(); setSaving(true); setError(""); setNotice(""); try { await updateProfile({ email, username: username || undefined, company_name: companyName || null, ...(newPassword ? { current_password: currentPassword, new_password: newPassword } : {}) }); setCurrentPassword(""); setNewPassword(""); setNotice("Profile updated."); } catch (cause) { setError(cause.message); } finally { setSaving(false); } }
  return <><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow text-blue-600">Workspace identity</p><h1 className="mt-2 text-3xl font-bold">Profile and account settings.</h1><p className="mt-2 text-sm text-text-secondary">Keep your workspace name, sign-in information, and password current.</p></div><UserRound className="text-blue-600" size={28} /></div>{error && <p className="mt-5 rounded-lg border border-rose-400/25 bg-rose-400/10 px-4 py-3 text-sm text-rose-500">{error}</p>}{notice && <p className="mt-5 rounded-lg border border-emerald-400/25 bg-emerald-400/10 px-4 py-3 text-sm text-emerald-600">{notice}</p>}<form onSubmit={save} className="mt-7 grid gap-6 xl:grid-cols-[minmax(0,1fr)_minmax(18rem,0.65fr)]"><section className="glass-card rounded-lg"><p className="eyebrow">Profile</p><h2 className="mt-1 text-xl font-semibold">Workspace details</h2><div className="mt-5 grid gap-4"><label className="text-sm font-medium">Workspace name<input className="mt-2 w-full rounded-lg border border-border bg-bg-base p-3" value={companyName} onChange={(event) => setCompanyName(event.target.value)} maxLength="255" /></label><label className="text-sm font-medium">Username<input className="mt-2 w-full rounded-lg border border-border bg-bg-base p-3" value={username} onChange={(event) => setUsername(event.target.value)} minLength="3" maxLength="32" /></label><label className="text-sm font-medium">Sign-in email<input className="mt-2 w-full rounded-lg border border-border bg-bg-base p-3" type="email" value={email} onChange={(event) => setEmail(event.target.value)} required /></label></div></section><section className="glass-card rounded-lg"><KeyRound className="text-violet-600" size={20} /><p className="eyebrow mt-4">Security</p><h2 className="mt-1 text-xl font-semibold">Change password</h2><label className="mt-5 block text-sm font-medium">Current password<input className="mt-2 w-full rounded-lg border border-border bg-bg-base p-3" type="password" value={currentPassword} onChange={(event) => setCurrentPassword(event.target.value)} /></label><label className="mt-4 block text-sm font-medium">New password<input className="mt-2 w-full rounded-lg border border-border bg-bg-base p-3" type="password" minLength="12" value={newPassword} onChange={(event) => setNewPassword(event.target.value)} /></label><p className="mt-3 text-xs text-text-secondary">Leave password fields empty to update profile details only.</p></section><div className="xl:col-span-2"><button disabled={saving} className="inline-flex min-h-11 items-center gap-2 rounded-lg bg-accent-primary px-5 text-white disabled:opacity-60">{saving && <LoaderCircle size={16} className="animate-spin" />}{saving ? "Saving..." : "Save settings"}</button></div></form></>;
}
